# sets variables $(TestDataUrl) and $(TestDataChecksum)

parameters:
  TestDataUrl: https://onnxruntimetestdata.blob.core.windows.net/models/20190419.zip
  TestDataChecksum: f09be50259b0ffdf4aee2e455cf22168

steps:
- task: CmdLine@1
  displayName: 'Set TestDataUrl variable'
  inputs:
    filename: echo
    arguments: '##vso[task.setvariable variable=TestDataUrl;]${{parameters.TestDataUrl}}'

- task: CmdLine@1
  displayName: 'Set TestDataChecksum variable'
  inputs:
    filename: echo
    arguments: '##vso[task.setvariable variable=TestDataChecksum;]${{parameters.TestDataChecksum}}'
